-- V4 — Christian: auditoría de seguridad e integración con módulos consumidores
-- Tablas: auditoria_seguridad, cliente_servicio, scope, cliente_servicio_scope, outbox
-- SPEC-12: Registro de auditoría
-- SPEC-17: Tokens de servicio e introspección

-- ═══════════════════════════════════════════════════════════════
-- ENUM: actor_tipo
-- Tipo de actor que realiza una acción auditada
-- ═══════════════════════════════════════════════════════════════

CREATE TYPE "actor_tipo" AS ENUM (
	'USUARIO',
	'MODULO',
	'SISTEMA'
);

-- ═══════════════════════════════════════════════════════════════
-- TABLA: auditoria_seguridad
-- Solo-anexado, sin UPDATE/DELETE para la app, retención 90 días (SPEC-12)
-- Sin FK a usuario a propósito: el registro sobrevive a la cuenta
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS "auditoria_seguridad" (
	"id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"fecha" timestamptz NOT NULL DEFAULT now(),
	"accion" varchar(50) NOT NULL,
	"resultado" resultado NOT NULL,
	"actor_tipo" actor_tipo NOT NULL,
	"actor_id" varchar(64),
	"objetivo_usuario_id" uuid,
	"ip" varchar(45),
	"agente" varchar(255),
	"detalle" jsonb,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "auditoria_seguridad" IS 'Solo-anexado, sin UPDATE/DELETE para la app, retención 90 días configurable (SPEC-12). Sin FK a usuario a propósito: el registro sobrevive a la cuenta.';
COMMENT ON COLUMN "auditoria_seguridad"."actor_id" IS 'uuid usuario o client_id';

-- Las consultas de SPEC-13 filtran por un campo y ordenan por fecha descendente.
CREATE INDEX "idx_auditoria_objetivo_fecha" ON "auditoria_seguridad" ("objetivo_usuario_id", "fecha");
CREATE INDEX "idx_auditoria_actor_fecha" ON "auditoria_seguridad" ("actor_id", "fecha");
CREATE INDEX "idx_auditoria_accion_fecha" ON "auditoria_seguridad" ("accion", "fecha");
CREATE INDEX "idx_auditoria_fecha" ON "auditoria_seguridad" ("fecha");

-- Solo anexado (RF-12.4, ESC-12.6): ningún UPDATE, venga de quien venga.
CREATE OR REPLACE FUNCTION "fn_auditoria_solo_anexado"() RETURNS trigger AS $$
BEGIN
	RAISE EXCEPTION 'auditoria_seguridad es de solo anexado: no admite UPDATE';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "tg_auditoria_solo_anexado"
BEFORE UPDATE ON "auditoria_seguridad"
FOR EACH ROW EXECUTE FUNCTION "fn_auditoria_solo_anexado"();

-- ═══════════════════════════════════════════════════════════════
-- TABLA: cliente_servicio
-- Los seis módulos consumidores (SPEC-17)
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS "cliente_servicio" (
	"client_id" varchar(50) NOT NULL,
	"client_secret_hash" varchar(255) NOT NULL,
	"nombre" varchar(100),
	"activo" boolean NOT NULL DEFAULT true,
	PRIMARY KEY("client_id")
);
COMMENT ON TABLE "cliente_servicio" IS 'Los seis módulos consumidores (SPEC-17). client_secret siempre hasheado.';

-- ═══════════════════════════════════════════════════════════════
-- TABLA: scope
-- Catálogo de scopes que emitimos (SPEC-17, acuerdo A4)
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS "scope" (
	"codigo" varchar(50) NOT NULL,
	"audiencia" varchar(50) NOT NULL,
	"descripcion" varchar(255),
	PRIMARY KEY("codigo"),
	CONSTRAINT "ck_scope_codigo" CHECK ("codigo" ~ '^[a-z_]+(:[a-z_]+)+$'),
	CONSTRAINT "ck_scope_audiencia" CHECK ("audiencia" ~ '^api-[a-z]+$')
);
COMMENT ON TABLE "scope" IS 'Catálogo de scopes que emitimos (SPEC-17, acuerdo A4). El dueño de la API lo define y lo valida; nosotros solo lo registramos y lo copiamos al token.';
COMMENT ON COLUMN "scope"."codigo" IS 'recurso:accion, p. ej. usuarios:leer, cotizaciones:calcular';
COMMENT ON COLUMN "scope"."audiencia" IS 'API dueña del scope, va al claim aud: api-seguridad, api-despacho…';

-- ═══════════════════════════════════════════════════════════════
-- TABLA: cliente_servicio_scope
-- Scopes concedidos por módulo (SPEC-17)
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS "cliente_servicio_scope" (
	"client_id" varchar(50) NOT NULL,
	"scope" varchar(50) NOT NULL,
	PRIMARY KEY("client_id", "scope")
);
COMMENT ON TABLE "cliente_servicio_scope" IS 'Scopes concedidos por módulo (SPEC-17).';
CREATE INDEX "idx_cliente_servicio_scope_scope" ON "cliente_servicio_scope" ("scope");

-- ═══════════════════════════════════════════════════════════════
-- TABLA: outbox
-- Outbox transaccional: correos asíncronos y eventos after-commit
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS "outbox" (
	"id" uuid NOT NULL DEFAULT gen_random_uuid(),
	"topico" varchar(100) NOT NULL,
	"payload" jsonb NOT NULL,
	"estado" varchar(20) NOT NULL DEFAULT 'PENDIENTE',
	"creado_en" timestamptz NOT NULL DEFAULT now(),
	"intentos" integer NOT NULL DEFAULT 0,
	"procesado_en" timestamptz,
	PRIMARY KEY("id"),
	CONSTRAINT "ck_outbox_estado" CHECK ("estado" IN ('PENDIENTE', 'ENVIADO', 'FALLIDO')),
	CONSTRAINT "ck_outbox_intentos" CHECK ("intentos" >= 0)
);
COMMENT ON TABLE "outbox" IS 'Outbox transaccional: correos asíncronos y eventos after-commit (SPEC-02/12/14).';
COMMENT ON COLUMN "outbox"."estado" IS 'PENDIENTE → ENVIADO, o FALLIDO al agotar los reintentos';
COMMENT ON COLUMN "outbox"."intentos" IS 'reintentos de envío del mensaje';
COMMENT ON COLUMN "outbox"."procesado_en" IS 'cuándo se despachó el mensaje';
CREATE INDEX "idx_outbox_estado_creado" ON "outbox" ("estado", "creado_en");

-- ═══════════════════════════════════════════════════════════════
-- FKs de cliente_servicio_scope
-- ═══════════════════════════════════════════════════════════════

ALTER TABLE "cliente_servicio_scope"
	ADD FOREIGN KEY("client_id") REFERENCES "cliente_servicio"("client_id")
	ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "cliente_servicio_scope"
	ADD FOREIGN KEY("scope") REFERENCES "scope"("codigo")
	ON UPDATE NO ACTION ON DELETE RESTRICT;
